# Generated by Django 3.0.3 on 2020-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabvoicemaild', '0003_auto_20191211_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='visual_voicemail',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='index_voicemail',
            field=models.TextField(default=0, null=True),
        ),
    ]
