# Generated by Django 3.0.3 on 2020-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabvoicemaild', '0004_auto_20200326_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='voicemail',
        ),
        migrations.AlterField(
            model_name='config',
            name='index_voicemail',
            field=models.TextField(default='aqi', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='visual_voicemail',
            field=models.TextField(default='nothing', null=True),
        ),
    ]
