"""
Django settings for nabweb project.

Generated by 'django-admin startproject' using Django 2.1.3.
"""

import os
from django.utils.translation import gettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# =========================
# SECURITY
# =========================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "+m)qk@&t%tlqj@o$jo$&egt34r7yu0fq4v!0o82&b9+b51ppyy",
)

# DEBUG via env
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS via env
allowed_hosts_env = os.getenv("DJANGO_ALLOWED_HOSTS", "")

if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",")]
else:
    ALLOWED_HOSTS = ["*"]

# sécurité en prod
if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError("ALLOWED_HOSTS must be set in production")

# =========================
# COOKIES
# =========================

CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_SAMESITE = None

# =========================
# APPLICATIONS
# =========================

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "nabd",
    "nab8balld",
    "nabbookd",
    "nabclockd",
    "nabmastodond",
    "nabsurprised",
    "nabtaichid",
    "nabweatherd",
    "nabairqualityd",
    "nabweb",
    "nabiftttd",
    "nabradio",
    "nabwebhook",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "nabweb.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nabweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "nabweb.wsgi.application"

# =========================
# DATABASE
# =========================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("PGDATABASE", "pynab"),
        "USER": os.getenv("PGUSER", "pynab"),
        "PASSWORD": os.getenv("PGPASSWORD", ""),
        "HOST": os.getenv("PGHOST", ""),
        "PORT": os.getenv("PGPORT", ""),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# =========================
# PASSWORD VALIDATION
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]

# =========================
# INTERNATIONALIZATION
# =========================

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("fr-fr", _("French")),
    ("de-de", _("German")),
    ("en-us", _("U.S. English")),
    ("en-gb", _("British English")),
    ("it-it", _("Italian")),
    ("es-es", _("Spanish")),
    ("ja-jp", _("Japanese")),
    ("pt-br", _("Brazilian Portuguese")),
]

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True

# =========================
# STATIC
# =========================

STATIC_URL = "/static/"